apiVersion: v1
kind: Service
metadata:
  labels:
    app: mastersecu
  name: mastersecu
spec:
  ports:
    - nodePort: 30945
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: mastersecu
  type: LoadBalancer